### ISSUE TITLE
For the not-square attn (How to generate 'Relative position bias' when 'attn' is a non-square matrix ?)

### ISSUE THREAD

**Issue by blackcow** [microsoft/Swin-Transformer#139]
https://github.com/microsoft/Swin-Transformer/blob/6bbd83ca617db8480b2fb9b335c476ffaf5afb1a/models/swin_transformer.py#L129

When the dimensions of Q, K are not the same (i.e., N_q is not equal to N_k), the generated attn is non-square, so I resize the relative_position_bias. I tried, but the relative_position_bias does not work as expected.

How should I generate relative_position_bias for this case? Looking forward to your reply : )

**Comment by zeliu98** [comment]
Hi,
We first defined a **relative_position_bias_table** for each possible **relative** position per head.
 https://github.com/microsoft/Swin-Transformer/blob/fa36255a62b37bc37c05133d7af5704b88d1ad3c/models/swin_transformer.py#L89-L90
 In our case, all possible relative positions are:

| (-Wh+1, -Ww+1) | ... | (-Wh+1, -2) | (-Wh+1, -1) | (-Wh+1, 0) | (-Wh+1, 1) | (-Wh+1, 2) | ... |(-Wh+1, Ww-1) |
| :----: |  :----: | :----: | :----: | :----: | :----: | :----: | :----: | :----: |
|...|...|...|...|...|...|...|...|...|
| (0, -Ww+1) | ... | (0, -2) | (0, -1) | (0, 0) | (0, 1) | (0, 2) | ... | (0, Ww-1) |
|...|...|...|...|...|...|...|...|...|
| (Wh-1, -Ww+1) | ... | (Wh-1, -2) | (Wh-1, -1) | (Wh-1, 0) | (Wh-1, 1) | (Wh-1, 2) | ... | (0, Ww-1) |

where Wh/Ww represent the height/width of the window. So the total number of all possible relative positions are(2xWh-1) x (2xWw-1).

With the **relative_position_bias_table**, we now can select the corresponding value(relative_position_bias) from it based on the relative position (∆h,∆w) of each **q** and **k**:
https://github.com/microsoft/Swin-Transformer/blob/fa36255a62b37bc37c05133d7af5704b88d1ad3c/models/swin_transformer.py#L93-L103

https://github.com/microsoft/Swin-Transformer/blob/fa36255a62b37bc37c05133d7af5704b88d1ad3c/models/swin_transformer.py#L126

Note that because pytorch doesn't support selecting the relative_position_bias_table using a 2D relative position matrix, so we first change it to a 1D index.

As for your question, I have the following suggestions:
- First, list all possible relative positions of Q and K and then define the relative_position_bias_table.
- Second, select the corresponding value from the relative_position_bias_table based on the relative position of each q and k.

Hope it can help😊.
