### ISSUE TITLE
Error!!

### ISSUE THREAD

**Issue by yutinyang** [microsoft/Swin-Transformer#17]
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

**Comment by yutinyang** [comment]
Thanks. I have changed my configuration to solve this problem.

**Comment by daixiaolei623** [comment]
@yutinyang 
Hi 
when i run"python tools/test.py /home/dai/code/semantic_segmentation/25/Swin-Transformer-Semantic-Segmentation-main/configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k.py /home/dai/code/semantic_segmentation/25/Swin-Transformer-Semantic-Segmentation-main/upernet_swin_base_patch4_window7_512x512.pth --eval mIoU" in semantic segmentation, i got the following error:
"AssertionError: fused_bias_leakyrelu miss in module _ext"
Could you please tell me how to solve it.
thank you.

**Comment by daixiaolei623** [comment]
@yutinyang 
I run in ubuntu, cuda10.1, anaconda3

**Comment by yutinyang** [comment]
> python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main.py \
> --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path <imagenet-path> --batch-size 128

I used "python -m torch.distributed.launch --nproc_per_node 4 --master_port 12345  main.py \
--cfg configs/swin_tiny_patch4_window7_224.yaml --data-path <my: imagenet-path> --batch-size 128" ,It doesn't work.

Error in line 310; 
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

**Comment by guolonghui** [comment]
@yutinyang Hi,the problem is solved? I also encountered this problem now,like the below
_### (swin) G:\win10_tensorflow\Swin-Transformer-main>python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345 main.py --eval --cfg configs/swin_base_patch4_window7_224.yaml --resume swin_base_patch4_window7_224.pth --data-path G:\image\imagenet
=> merge config from configs/swin_base_patch4_window7_224.yaml
RANK and WORLD_SIZE in environ: 0/1
Traceback (most recent call last):
  File "main.py", line 312, in <module>
    torch.distributed.init_process_group(backend='nccl', init_method='env://', world_size=world_size, rank=rank)
  File "G:\ProgramData\Anaconda3\envs\swin\lib\site-packages\torch\distributed\distributed_c10d.py", line 434, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "G:\ProgramData\Anaconda3\envs\swin\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\envs\swin\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "G:\ProgramData\Anaconda3\envs\swin\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\ProgramData\Anaconda3\envs\swin\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
    main()
  File "G:\ProgramData\Anaconda3\envs\swin\lib\site-packages\torch\distributed\launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\ProgramData\\Anaconda3\\envs\\swin\\python.exe', '-u', 'main.py', '--local_rank=0', '--eval', '--cfg', 'configs/swin_base_patch4_window7_224.yaml', '--resume', 'swin_base_patch4_window7_224.pth', '--data-path', 'G:\\image\\imagenet']' returned non-zero exit status 1._

**Comment by liyiersan** [comment]
> @yutinyang Hi,the problem is solved? I also encountered this problem now,like the below
> _### (swin) G:\win10_tensorflow\Swin-Transformer-main>python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345 main.py --eval --cfg configs/swin_base_patch4_window7_224.yaml --resume swin_base_patch4_window7_224.pth --data-path G:\image\imagenet
> => merge config from configs/swin_base_patch4_window7_224.yaml
> RANK and WORLD_SIZE in environ: 0/1
> Traceback (most recent call last):
> File "main.py", line 312, in
> torch.distributed.init_process_group(backend='nccl', init_method='env://', world_size=world_size, rank=rank)
> File "G:\ProgramData\Anaconda3\envs\swin\lib\site-packages\torch\distributed\distributed_c10d.py", line 434, in init_process_group
> init_method, rank, world_size, timeout=timeout
> File "G:\ProgramData\Anaconda3\envs\swin\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
> raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
> RuntimeError: No rendezvous handler for env://
> Traceback (most recent call last):
> File "G:\ProgramData\Anaconda3\envs\swin\lib\runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "G:\ProgramData\Anaconda3\envs\swin\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "G:\ProgramData\Anaconda3\envs\swin\lib\site-packages\torch\distributed\launch.py", line 260, in main() File "G:\ProgramData\Anaconda3\envs\swin\lib\site-packages\torch\distributed\launch.py", line 256, in main cmd=cmd) subprocess.CalledProcessError: Command '['G:\ProgramData\Anaconda3\envs\swin\python.exe', '-u', 'main.py', '--local_rank=0', '--eval', '--cfg', 'configs/swin_base_patch4_window7_224.yaml', '--resume', 'swin_base_patch4_window7_224.pth', '--data-path', 'G:\image\imagenet']' returned non-zero exit status 1._

This works for me. https://blog.csdn.net/qq_36622589/article/details/117913064

**Comment by guolonghui** [comment]
把GCC版本调低，我的是改成6.5就能用了

**Comment by youngdaragon** [comment]
Hi, I used ''(swin_transformer)python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345 main.py --eval \
--cfg configs/swin_base_patch4_window7_224.yaml --resume swin_base_patch4_window7_224.pth --data-path myimage --epochs 10 --batch-size 12'' It dosen't work.

Traceback (most recent call last):
  File "main.py", line 357, in <module>
    main(config)
  File "main.py", line 89, in main
    model, optimizer = amp.initialize(model, optimizer, opt_level=config.AMP_OPT_LEVEL)
AttributeError: 'NoneType' object has no attribute 'initialize'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 93793) of binary: /home/kimyongtae/Downloads/myAnaconda/envs/myenv/bin/python
Traceback (most recent call last):
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-03-04_13:30:27
  host      : kimyongtae-B250-HD3
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 93793)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

How can I solve it?

**Comment by YumnaMemon** [comment]
> Lower the GCC version, mine is changed to 6.5 and it will work.

how?
